config/routes.rb
Rails.application.routes.draw do
  root                     'posts#index'
  get     'create_post' => 'posts#new'
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'
  get     'about'       => 'static_pages#about'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :body_text, presence: true, length: { maximum: 500 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	has_many :posts
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness:
	has_secure_password
	validates :password, length: { minimum: 6}

	

	def User.digest(token)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(token, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include PostsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  def index
  	@posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
    @post.user_id = current_user.id
  	if @post.save
  		flash[:success] = "Post created"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end



  private

  def post_params
  	params.require(:post).permit(:body_text)
  end

  def require_login
    unless logged_in?
      flash[:danger] = "You must be logged in to access this page"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
  		log_in(@user)
      remember(@user)
  		flash[:success] = "Welcome #{@user.name}"
  		redirect_to root_url
  	else
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = "")
		base_title = "Members Only"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in(user)
				@current_user = user
			end
		end	
	end



	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget 
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<p>Created by Kevin Mulhern, find the code on github <a href="https://github.com/KevinMulhern/members-only">Here</a></p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Members Only", root_path, id: "logo" %>
	<nav>
	<ul class="nav nav-pills navbar-right">
		<li><%= link_to "Home", root_path %> </li>
		<li><%= link_to "About", about_path %></li>
		<% if logged_in? %>
			<li><%= link_to "Log out", logout_path, method: "delete" %></li>
		<% else %>
			<li><%= link_to "Log in", login_path %></li>
		<% end %>
	</ul>
	</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |message_type, message| %>
		<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	<% end %>
</div>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "Home") %>
<h1 class=>Latest Posts</h1>
<% if logged_in? %>
	<%= link_to "Create New Post", create_post_path, class: "create-post col-md-2 col-md-offset-3" %>
<% end %>

<div class="row">
	<div class="col-md-6 col-md-offset-3 posts">
		<% @posts.reverse_each do |p| %>
			<div class="index-posts">
				<p><%= p.body_text %> </p>
					<p class="author"><span>Written by:</span> <% if logged_in? %>
								<%= p.user.name %>
							<% else %>
								<%= "Log in to view" %></p> 
							<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Create Post") %>
<h1>Create a New Post</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@post) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.text_area :body_text, class: 'form-control', rows: "6" %>

			<%= f.submit "Create Post", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Members Only</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3 well">	
  		<p>
    		Members only is a club house website where only logged-in users can view the authors of posts. Users that are not logged-in can only see the body text of the posts and are left wondering who wrote them.
    	</p>

    	<p>
    		At present this site does not have any signup functionality. But please use the credentials provided below to enter the site and play around with it, thanks for visiting. 
    	</p>

    	<h3>User Credentials:</h3>
    	<table class="table table-bordered">
    		<thead>
    			<tr>
    				<th>Email:</th>
    				<th>Password:</th>
    			</tr>
    		<tbody>
    			<tr>
    				<td>kevin@email.com</td>
    				<td>foobar</td>
    			</tr>
    			<tr>
    				<td>sterling@email.com</td>
    				<td>password</td>
    			</tr>
    		</tbody>

    		</thead>

    	</table>
	</div>
</div>